name: "\U0001F41E Bug report"
description: Report an issue with massCode
title: "[Bug]: "
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true
  - type: textarea
    id: reproduse
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      placeholder: How to reproduce the bug
      value: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ..
        4. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: e.g. 2.0.0, 2.0.0-beta.6
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: OS
      description: What version of OS are you using?
      placeholder: e.g. macOS Monterey 12.1, Windows 10
  - type: checkboxes
    id: validation
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
          required: true