name: "\U0001F41E Bug report"
description: Report an issue with massCode
title: "[Bug]: "
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduse
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      placeholder: Tell us what you see!
      value: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ..
        4. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: e.g. 2.0.0, 2.0.0-beta.6
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: OS
      description: What version of OS are you using?
      placeholder: e.g. macOS Monterey 12.1, Windows 10
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true